services:
  student-app:
    container_name: student-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4173:80
  student-storybook:
    container_name: student-storybook
    build:
      context: .
      dockerfile: storybook.dockerfile
    ports:
      - 6006:80
